# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-10 13:12
from __future__ import unicode_literals

import base_user.tools.common
from django.conf import settings
import django.contrib.auth.models
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0009_auto_20170910_1712'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='parol')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='son dəfə daxil olub')),
                ('is_superuser', models.BooleanField(default=False, help_text='İstifadəçiyə bütün icazələri verir.', verbose_name='superistifadəçi statusu')),
                ('username', models.CharField(help_text='Tələb olunur. 75 simvol və ya az. Hərflər, Rəqəmlər və @/./+/-/_ simvollar.', max_length=100, unique=True, validators=[django.core.validators.RegexValidator('^[\\w.@+-]+$', 'Düzgün istifadəçi adı daxil edin.', 'yanlışdır')], verbose_name='istifadəçi adı')),
                ('first_name', models.CharField(blank=True, max_length=255, verbose_name='ad')),
                ('last_name', models.CharField(blank=True, max_length=255, verbose_name='soyad')),
                ('email', models.EmailField(max_length=255, verbose_name='e-poçt ünvanı')),
                ('birthday', models.DateField(default=django.utils.timezone.now, verbose_name='ad günü')),
                ('father_name', models.CharField(blank=True, max_length=255, null=True)),
                ('diplom_number', models.CharField(blank=True, max_length=255, null=True)),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to=base_user.tools.common.get_user_profile_photo_file_name)),
                ('profile_picture_1', models.ImageField(blank=True, null=True, upload_to=base_user.tools.common.get_user_profile_photo_file_name)),
                ('profile_picture_2', models.ImageField(blank=True, null=True, upload_to=base_user.tools.common.get_user_profile_photo_file_name)),
                ('gender', models.IntegerField(choices=[(1, 'Kişi'), (2, 'Qadın')], default=1, verbose_name='cinsi')),
                ('verified', models.BooleanField(default=False, verbose_name='Təstiqlənmə')),
                ('code', models.CharField(blank=True, max_length=20, null=True, verbose_name='Kod')),
                ('unvani', models.CharField(blank=True, max_length=255, null=True, verbose_name='ünvanı')),
                ('phone', models.CharField(blank=True, max_length=100, null=True, verbose_name='Telefonu')),
                ('study', models.CharField(blank=True, max_length=200, null=True, verbose_name='Təhsili')),
                ('slug', models.SlugField(blank=True, null=True)),
                ('usertype', models.IntegerField(blank=True, choices=[(1, 'Həkim'), (2, 'Normal user'), (3, 'Administrator')], null=True, verbose_name='Sistemdəki statusu')),
                ('is_staff', models.BooleanField(default=False, help_text='İstifadəçinin admin panelinə daxil olub, olmayacağını təyin edir.', verbose_name='admin statusu')),
                ('is_active', models.BooleanField(default=True, help_text='İstifadəçinin aktiv və ya qeyri-aktiv olmasını təyin edir. Hesabları silmək əvəzinə bundan istifadə edin.', verbose_name='Aktiv')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='qoşulub')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='qruplar')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='səlahiyyətləri')),
            ],
            options={
                'verbose_name': 'İstifadəçi',
                'verbose_name_plural': 'İstifadəçilər',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='UserConfrimationKeys',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(blank=True, max_length=255, null=True)),
                ('expired', models.BooleanField(default=False)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Təstiqlənmiş user',
                'verbose_name_plural': 'Təstiqlənmiş userlər',
                'ordering': ('-date',),
            },
        ),
    ]
