"""
Django settings for tezsagal_project project.

Generated by 'django-admin startproject' using Django 1.11.3.

For more information on this file, see
https://docs.djangoproject.com/en/1.11/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.11/ref/settings/
"""

import os
from django.utils.translation import ugettext_lazy as _
# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.11/howto/deployment/checklist/
PROD = False
if '/doctor/' in BASE_DIR:
    PROD = True

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'n7t$#=i*_lu+sy4)rw!he^1i8@dp_%)yy5v*u$#1@(fi1w^)yb'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True if not PROD else False

ALLOWED_HOSTS = ['www.tezsagal.com','tezsagal.com','tezsagal.az','www.tezsagal.az'] if PROD else ['*']


# Email confirimation
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_HOST_USER = 'info@tezsagal.com'
EMAIL_HOST_PASSWORD = 'tezsagalinfo12345'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
DEFAULT_FROM_EMAIL = EMAIL_HOST_USER
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'

# Default Django user model Override
AUTH_USER_MODEL = "base_user.MyUser"

# Locale translation files here
LOCALE_PATHS = (
    os.path.join(BASE_DIR, 'locale'),
)

# Default login required
LOGIN_URL = '/az/account/'
# Application definition
# Milli kart Transaction registration

MID = 'tezsagal' # base Merchant ID
PAYMENT_SECRET_KEY = 'JKAO84NA93HD0372KS2LHW3UDFSDF20A' # value is given by Millikart

TEST_MILLI_KART_PAYMENT_HTTP = 'http://test.millikart.az:8513/gateway/payment/register'
TEST_MILLI_KART_PAYMENT_HTTPS = 'https://test.millikart.az:7444/gateway/payment/register'
MILLI_KART_PAYMENT = 'https://pay.millikart.az/gateway/payment/register'

TEST_MILLI_KART_PAYMENT_STATUS_HTTP = 'http://test.millikart.az:8513/gateway/payment/status'
TEST_MILLI_KART_PAYMENT_STATUS_HTTPS = 'https://test.millikart.az:7444/gateway/payment/status'
MILLI_KART_PAYMENT_STATUS = 'https://pay.millikart.az/gateway/payment/status'



INSTALLED_APPS = [
    'modeltranslation',
    'suit',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sites',
    'django.contrib.flatpages',
    'widget_tweaks',
    'base_user.apps.BaseUserConfig',
    'doctor.apps.DoctorConfig',
    # 'doctor.templatetags.doctor_tags',
    'mapwidgets',
    'ckeditor',
    'ckeditor_uploader',
    'geoposition',
    # 'modeltranslation',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'tezsagal_project.middleware.force_default_middleware.force_default_language_middleware',
    'tezsagal_project.middleware.security.ChangeHeader',
    'django.middleware.locale.LocaleMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.contrib.flatpages.middleware.FlatpageFallbackMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'tezsagal_project.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'tezsagal_project.wsgi.application'

SITE_ID = 1
# Database
# https://docs.djangoproject.com/en/1.11/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    }
}

# Django Suit config
SUIT_CONFIG = {
    'ADMIN_NAME':'Tezsagal Administrasiya',

}
# Password validation
# https://docs.djangoproject.com/en/1.11/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
MODELTRANSLATION_DEFAULT_LANGUAGE = 'az'
# https://docs.djangoproject.com/en/1.11/topics/i18n/

LANGUAGE_CODE = 'az'

LANGUAGES = (
    ('az', _('Aze')),
    ('ka', _('Geo')),
    ('ru', _('Rus')),
)


TIME_ZONE = 'Asia/Baku'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.11/howto/static-files/

STATIC_URL = '/static/'
# if PROD:
#
#     STATIC_ROOT = 'static'
# else:
    # STATICFILES_DIRS = [
    #     os.path.join(BASE_DIR, "static"),
    #     '/home/munis/Documents/tezsagal',
    # ]
    # STATIC_ROOT = os.path.join(BASE_DIR, 'static')



CKEDITOR_JQUERY_URL = '//ajax.googleapis.com/ajax/libs/jquery/2.1.1/jquery.min.js'
CKEDITOR_UPLOAD_PATH = "uploads/"

CKEDITOR_CONFIGS = {
    'awesome_ckeditor': {
        'toolbar': 'full',
        'height': 300,
        'width': 600,
    },
    'default': {
        'toolbar': 'full',
        'height': 300,
        'width': 600,
    },
}

STATICFILES_DIRS = (
    os.path.join(BASE_DIR, 'static'),
)
STATIC_ROOT = os.path.join(BASE_DIR, 'sitestatic')


MEDIA_URL = '/media/'
MEDIA_ROOT = 'media'

LOG_ROOT = os.path.join(BASE_DIR,'logs')
LOG_LEVEL = 'DEBUG'


GEOPOSITION_GOOGLE_MAPS_API_KEY = 'AIzaSyAc2KAE8d9QEtMDLQTLayqzba7yFT-uO6o'
GEOPOSITION_MAP_OPTIONS = {
    'minZoom': 3,
    'maxZoom': 15,
}

GEOPOSITION_MARKER_OPTIONS = {
    'cursor': 'move'
}


LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,  # True,
    'formatters': {
        'standard': {
            'format': '%(asctime)s [%(levelname)s] %(name)s:=> %(message)s',
        },
        'focused': {
            'format': '\n----------------------\n%(asctime)s [%(levelname)s] %(name)s:=> %(message)s \n----------------------',
        },
    },
    'handlers': {
        'request_handler': {
            'level': LOG_LEVEL,
            'class': 'logging.FileHandler',
            'filename': '%s/django_requests.log' % LOG_ROOT,
            'formatter': 'standard',
        },
    },
    'loggers': {
        'django.request': {
            'handlers': ['request_handler'],
            'level': LOG_LEVEL,
            'propagate': True,
        },
    }
}