# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-10-03 14:22
from __future__ import unicode_literals

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0003_auto_20170815_2011'),
        ('doctor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StaticPage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(db_index=True, max_length=100, verbose_name='URL')),
                ('title', models.CharField(max_length=200, verbose_name='başlıq')),
                ('title_az', models.CharField(max_length=200, null=True, verbose_name='başlıq')),
                ('title_ka', models.CharField(max_length=200, null=True, verbose_name='başlıq')),
                ('title_ru', models.CharField(max_length=200, null=True, verbose_name='başlıq')),
                ('content', ckeditor_uploader.fields.RichTextUploadingField()),
                ('content_az', ckeditor_uploader.fields.RichTextUploadingField(null=True)),
                ('content_ka', ckeditor_uploader.fields.RichTextUploadingField(null=True)),
                ('content_ru', ckeditor_uploader.fields.RichTextUploadingField(null=True)),
                ('enable_comments', models.BooleanField(default=False, verbose_name='şərhlər olsun')),
                ('template_name', models.CharField(blank=True, help_text="Example: 'staticpages/contact_page.html'. If this isn't provided, the system will use 'staticpages/default.html'.", max_length=70, verbose_name='şablonun adı')),
                ('registration_required', models.BooleanField(default=False, help_text='Əgər bura quş qoysanız, ancaq qeydiyyatdan keçib sayta daxil olmuş istifadəçilər bu səhifəni görə biləcəklər.', verbose_name='ancaq qeydiyyatlılar üçün')),
                ('sites', models.ManyToManyField(to='sites.Site', verbose_name='saytlar')),
            ],
            options={
                'verbose_name_plural': 'static pages',
                'ordering': ('url',),
                'verbose_name': 'static page',
            },
        ),
    ]
