# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-09-11 06:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0002_doctor_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='rate',
            field=models.DecimalField(decimal_places=5, default=0.0, max_digits=19),
        ),
    ]
