# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-12-03 15:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0003_auto_20171129_1146'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentWorkCountry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('month_count', models.IntegerField()),
                ('quantity', models.FloatField(default=0)),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctor.Currency')),
            ],
        ),
        migrations.RemoveField(
            model_name='workcountry',
            name='currency',
        ),
        migrations.RemoveField(
            model_name='workcountry',
            name='quantity',
        ),
        migrations.AddField(
            model_name='doctor',
            name='payment_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Ödəniş Tarixi'),
        ),
        migrations.AddField(
            model_name='paymentworkcountry',
            name='work_country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctor.WorkCountry'),
        ),
        migrations.AlterUniqueTogether(
            name='paymentworkcountry',
            unique_together=set([('work_country', 'month_count')]),
        ),
    ]
